name: graphql_server2
version: 6.4.0
description: Base package for implementing GraphQL servers. You might prefer `package:angel3_graphql`, the fastest way to implement GraphQL backends in Dart.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/graphql_dart/tree/master/packages/graphql_server

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  angel3_serialize: ^8.0.0
  graphql_schema2: ^6.0.0
  graphql_parser2: ^6.0.0
  collection: ^1.17.0
  meta: ^1.9.0
  recase: ^4.1.0
  stream_channel: ^2.1.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
