name: graphql_parser2
version: 6.4.0
description: Parses GraphQL queries and schemas. Also includes classes for the GraphQL AST.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/graphql_dart/tree/master/packages/graphql_parser
environment:
  sdk: '>=3.8.0 <5.0.0'
dependencies:
  charcode: ^1.3.1
  source_span: ^1.10.0
  string_scanner: ^1.2.0
dev_dependencies:
  matcher: ^0.12.10
  lints: ^6.0.0
  test: ^1.24.0
