name: angel3_graphql
version: 8.1.0
description: The fastest and easiest way to get a GraphQL backend in Dart, using Angel3.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/graphql_dart/tree/master/packages/angel_graphql
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_file_service: ^8.0.0
  angel3_framework: ^8.0.0
  angel3_container: ^8.0.0
  angel3_websocket: ^8.1.0
  angel3_validate: ^8.0.0
  graphql_parser2: ^6.0.0
  graphql_schema2: ^6.0.0
  graphql_server2: ^6.0.0
  http_parser: ^4.0.0
  web_socket_channel: '>=2.1.0 <2.4.1'
  collection: ^1.17.0
dev_dependencies:
  angel3_serialize: ^8.0.0
  file: ^7.0.0
  logging: ^1.2.0
  lints: ^3.0.0
# dependency_overrides:
#   graphql_server2:
#     path: ../graphql_server
#   graphql_parser2:
#     path: ../graphql_parser
#   graphql_schema2:
#     path: ../graphql_schema
