name: graphql_generator2
version: 6.2.1
description: Generates GraphQL schemas from Dart classes, for use with pkg:graphql_server2.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/graphql_dart/tree/master/packages/graphql_generator
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  analyzer: ^6.5.0
  angel3_model: ^8.0.0
  angel3_serialize_generator: ^8.2.0
  graphql_schema2: ^6.2.0
  build: ^2.4.0
  build_config: ^1.1.0
  code_builder: ^4.5.0
  recase: ^4.1.0
  source_gen: ^1.3.0
  collection: ^1.17.0
dev_dependencies:
  build_runner: ^2.4.0
  lints: ^4.0.0
# dependency_overrides:
#   graphql_schema2:
#     path: ../graphql_schema


