name: graphql_generator2
version: 6.4.0
description: Generates GraphQL schemas from Dart classes, for use with pkg:graphql_server2.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/graphql_dart/tree/master/packages/graphql_generator
environment:
  sdk: '>=3.8.0 <5.0.0'
dependencies:
  analyzer: ^7.7.0
  angel3_model: ^8.0.0
  angel3_serialize_generator: ^8.2.0
  graphql_schema2: ^6.2.0
  build: ^3.0.0
  build_config: ^1.2.0
  code_builder: ^4.11.0
  recase: ^4.1.0
  source_gen: ^3.1.0
  collection: ^1.17.0
dev_dependencies:
  build_runner: ^2.7.0
  lints: ^6.0.0


