name: graphql_schema2
version: 6.1.0
description: An implementation of GraphQL's type system in Dart. Basis of graphql_server2.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/graphql_dart/tree/master/packages/graphql_schema
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection: ^1.17.0
  meta: ^1.9.0
  source_span: ^1.10.0
  quiver: ^3.2.0
dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
